language: node_js
node_js:
  - "node"
before_script:
  - npm install -g webpack
  - npm install -g mocha
  - npm install -g chai
  - npm start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
